spring:
  application:
    name: event-sourcing-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${POSTGRES_URL:${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}}/${DATABASE:postgres}}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      default_schema: ${DATABASE_SCHEMA:public}
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off


actor:
  cluster-name: event-sourcing-service
  conf: "actor/actor-system-${ACTOR_SYSTEM:local}.conf"
  supported-entities:
    User: "com.cxloyalty.gce.entity.UserEntity"
    Member: ""
    Membership: ""

logging:
  level.root: info
server:
  port: 8091
